name: enic_kz_web
description: "A new Flutter project."
publish_to: 'none' 

on: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/bolona.png
    - assets/image/kz.png
    - assets/image/news.jpeg
    - assets/image/partner.png
    - assets/image/partner1.jpg
    - assets/image/partner2.png
    - assets/image/map.jpg
